### ISSUE TITLE
View's usage of _TemplatedMixin means that dojox.mvc.Output doesn't work with the default expression character

### ISSUE THREAD

**Issue by itamarro** [dmachi/dojox_application#103]
Since the default expression character is "$", by default it doesn't work and throws an error in _TemplatedMixin (line ~ 80, { throw new Error(className+" template:"+key); } ) . Of course, if the expression character is set to something different, it works well.

Now, since dojox.mvc.Output is very likely to be often used with the dojox.app framework, IMHO this is rather confusing and should either be fixed or documented appropriately (this is not currently mentioned in the reference docs of dojox.mvc.Output)...

**Comment by edchat** [comment]
The problem also occurs with dojox/mvc/Repeat, but I don't think we should change the default now, since it would break any apps currently using dojox/mvc/Output or Repeat with the default.  So I will try to add something to the doc about needing to set the exprchar to something other than the default $ for dojox/mvc/Output and dojox/mvc/Repeat.

**Comment by itamarro** [comment]
Sure thing, thanks. Maybe in the future, we could have this work consistently somehow...

**Comment by cjolif** [comment]
The problem I think will arise in Dijit tempates as well. This is caused by $ being a special char in Dijit templates mechanism that we leverage. In 2.0 dojox/mvc should probably be change to use a different default. I think a enhancement request should be opened on dojox/mvc and this item should be closed because there is nothing we can do on dojox/app side here.

**Comment by itamarro** [comment]
Got you. Opened here: http://bugs.dojotoolkit.org/ticket/16511 . Thanks.
