### ISSUE TITLE
Django as Templating mechanism

### ISSUE THREAD

**Issue by maitriyogin** [dmachi/dojox_application#128]
Hi,
this is not really an issue as such but I was wondering if it's possible to use Django as the templating mechanism for the view templates?
This would be very very cool and bring this in line with the all the other mvc spa frameworks.
Cheers,
Maitriyogin

**Comment by cjolif** [comment]
Dojo provides a Django langage-based library called DTL (dojox/dtl). I suppose it should be usable in dojox/app templates. If you encounter specific issues please open a ticket with an example reproducing it so that we can investigate?

For question you can use dojo-interest mailing list:

http://mail.dojotoolkit.org/mailman/listinfo/dojo-interest

**Comment by maitriyogin** [comment]
Hi Christophe,
I'm aware of dojos/dtl but was more inquisitive as to how to include it in my "Views".  As they're not widgets in the traditional sense I was wondering how to mix the dtl stuff in, as it were..
Cheers,
Stephen.

On 11/28/12 17:08 , "Christophe Jolif" <notifications@github.com<mailto:notifications@github.com>> wrote:

Dojo provides a Django langage-based library called DTL (dojox/dtl). I suppose it should be usable in dojox/app templates. If you encounter specific issues please open a ticket with an example reproducing it so that we can investigate?

**Comment by cjolif** [comment]
ok @maitriyogin  I think I see your problem. What is easy to do is to use your DTL-enabled widgets inside a View template, but now I see that what you want to do it to directly treat the View template as a DTL template without intermediary widget. This should be feasible in theory as you should be able to sublcass and/or replace the default View by one of yours that would enable DTL-templating. Unfortunately due to some design flaws this is not yet feasible. However this is definitely something we are looking at fixing for 1.9. You can watch #131 for progress. Meanwhile you have to use an intermediary widget in your View template that is the DTL-enabled widget that will itself reference a DTL template.
