### ISSUE TITLE
The trick in model.js to dynamically load mvcModel and/or simpleModel does not seem to work

### ISSUE THREAD

**Issue by cjolif** [dmachi/dojox_application#48]
In todoApp, if I remove mvcModel from the dependencies the application is not initialized correctly anymore (in tablet mode at least). So it seems the dynamic loading of mvc vs simple model is not working correctly. Matybe we should simplify that code and rely on the fact the right dependency is loaded through dependencies array. That would help a future "build" system for dojox/app as well as the build system would "just" have to look for the dependencies instead of looking a various config parameters.

**Comment by cjolif** [comment]
cc @edchat

**Comment by edchat** [comment]
I agree, we should try to simplify that code and require that the dependency for the mvcModel or simpleModel is included in the dependencies list.

**Comment by dmachi** [comment]
I believe thats what it does now, it is only looking at the dependencies.  The intention is for it to scan the config and include other things as well, but none of that has been implemented as other pieces need to work first.  For example, it shouldn't automatically include all things from the entire app config and currently we don't give any control of that.  So for now, things should be in the dep list.

Dustin

**Comment by edchat** [comment]
So I guess I should have looked at the code again before making my comment, because it is not working as I thought it was.  And I should have had more comments in the code because it is confusing.  Anyway, I was wrong about what the deferred is being used for, it is not to wait for the require to complete, it is there to wait for the store's query to complete (in mvcModel or simpleModel) in case the query does not return immediately.

**Comment by cjolif** [comment]
@edchat I was refering to:

``` javascript
                var modelLoader = config[item].modelLoader ? config[item].modelLoader : "dojox/app/utils/simpleModel";
                require([modelLoader], // require the model type
                        function( requirement ){
                            def.resolve( requirement );
                        }
                );
```

does it really just manage the query to complete? I suspect it is not?

**Comment by edchat** [comment]
I guess I need to walk thru it again to make sure I understand what it is doing.  I was not saying that the "require([modelLoader]" part was used to manage the query to complete, I meant the "createModelPromise = modelCtor(config, params, item);" part.   

My understanding is that the require([modelLoader] will return immediately if the requirement is already loaded, and if it had not been loaded yet it will return a promise.  But I guess you are correct that since I do have code using  "when(def..", I am trying to handle the case when it has not already been loaded.  So if the dependency being in the config is required I guess I could simplify this code some, but I would still need to handle the case for the query not returning immediately.

**Comment by edchat** [comment]
Repeat of comment I made in the commit above: 
I agree that we should simplify this code, but the modelApp test and the layoutApp test were working without including the dependency for "dojox/app/utils/mvcModel", or "dojox/mvc/EditStoreRefListController", so those were being dynamically loaded. But there may have been some cases which were failing since the todoApp did not work for Christophe without the dependencies.

So unless anyone objects I will accept this pull request, and then I will update those tests to include the dependencies, and I will add a comment to the Release notes for 1.9.
